strings = {
    "start": (
        "🎵 **Elite Musico** — Your Premium Music Bot\n\n"
        "I can play music in your Telegram voice chats with stunning audio effects, "
        "smart queues, and beautiful now-playing cards.\n\n"
        "Use `/help` to see all commands."
    ),
    "help_header": "🎵 **Elite Musico** — Command Reference\n",
    "play_searching": "🔍 Searching for **{}**...",
    "play_downloading": "⬇️ Downloading **{}**...",
    "added_to_queue": "✅ Added to queue [#{}]: **{}**",
    "now_playing": "🎵 Now Playing",
    "queue_empty": "📭 Queue is empty.",
    "nothing_playing": "❌ Nothing is currently playing.",
    "paused": "⏸ Playback paused.",
    "resumed": "▶️ Playback resumed.",
    "skipped": "⏭ Skipped to next track.",
    "stopped": "⏹ Stopped and left voice chat.",
    "volume_set": "🔊 Volume set to {}%",
    "loop_none": "➡️ Loop disabled.",
    "loop_track": "🔂 Looping current track.",
    "loop_queue": "🔁 Looping entire queue.",
    "shuffled": "🔀 Queue shuffled!",
    "cleared": "🗑️ Queue cleared.",
    "no_voice_chat": "❌ No active voice chat. Join a voice chat first.",
    "join_vc": "❌ Please join a voice chat first.",
    "not_in_vc": "❌ You are not in the voice chat.",
    "not_admin": "❌ You need admin permissions for this.",
    "blacklisted": "🚫 You are blacklisted from using this bot.",
    "song_blacklisted": "🚫 That keyword is blacklisted.",
    "error": "❌ An error occurred: {}",
    "downloading": "⬇️ Downloading...",
    "processing": "⚙️ Processing...",
    "effect_applied": "✅ Effect `{}` applied!",
    "vote_skip_progress": "🗳 Vote to skip: {}/{} needed",
    "vote_skip_passed": "✅ Vote skip passed! Skipping...",
    "already_voted": "❌ You already voted.",
    "liked": "❤️ Added **{}** to your liked songs!",
    "unliked": "💔 Removed from liked songs.",
    "lang_set": "🌐 Language set to **{}**",
    "dj_added": "🎧 {} is now a DJ!",
    "dj_removed": "🎧 {} is no longer a DJ.",
    "user_blacklisted": "🚫 User {} has been blacklisted.",
    "user_unblacklisted": "✅ User {} has been unblacklisted.",
    "word_blacklisted": "🚫 Word `{}` added to blacklist.",
    "scheduled_set": "📅 Scheduled playback set for `{}`",
    "broadcast_sent": "📢 Broadcast sent to {} groups.",
    "auto_leave": "🔇 Leaving voice chat due to inactivity...",
    "reconnecting": "🔄 Reconnecting to voice chat...",
    "bass_boost_on": "🔊 Bass boost level {} enabled!",
    "bass_boost_off": "🔊 Bass boost disabled.",
    "karaoke_on": "🎤 Karaoke mode enabled!",
    "karaoke_off": "🎤 Karaoke mode disabled.",
    "nightcore_on": "🚀 Nightcore mode enabled!",
    "spatial_on": "🎶 3D Spatial audio enabled!",
    "normalizer_on": "🔔 Normalizer enabled!",
    "playlist_saved": "💾 Playlist `{}` saved with {} tracks!",
    "playlist_loaded": "📦 Loaded {} tracks from playlist `{}`",
    "playlist_not_found": "❌ Playlist `{}` not found.",
    "muted": "🔇 Bot muted.",
    "unmuted": "🔊 Bot unmuted.",
    "speed_set": "⏩ Playback speed set to {}×",
    "pitch_set": "🎼 Pitch shifted by {} semitones.",
    "reverb_on": "🌊 Reverb enabled!",
    "reverb_off": "🌊 Reverb disabled.",
    "eq_set": "🎵 EQ preset set to `{}`.",
}
